const frasesEngracadas = [
    "Por que o livro de matemática se suicidou? Porque tinha muitos problemas.",
    "O que a galinha foi fazer na igreja? Assistir à Missa do Galo!",
    "Qual é o cúmulo da rapidez? Fechar a porta do micro-ondas e cronometrar!",
    "O que o pato falou para a pata? Fica de quack!",
    "Qual é o rei dos queijos? O Rei queijo!",
    "Por que o pombo não usa o computador? Porque ele tem medo de mouse!",
    "Qual é o doce preferido do átomo? Pé de moléculas!",
    "O que o tomate foi fazer no banco? Tirar extrato ketchup!",
    "O que um muro falou para o outro? Nos encontramos no canto!",
    "Por que a bicicleta não consegue se levantar? Porque ela é dois-rodas!",
    "Qual é o nome do elevador mais educado? O elevador social!",
    "Por que a matemática é tão complexada? Porque tem muitos problemas.",
    "O que a banana suicida falou? Macacos me mordam!",    
    "Por que o gato foi ao dentista? Porque ele tinha miau hálito!",    
    "O que o avião falou para o helicóptero? Gira, gira, gira!",
    "Qual é o animal que está sempre gripado? O elefante, porque ele tem trom-bonquite!",
    "Por que o livro foi na academia? Para ficar com capa dura!",
    "O que o zero disse para o oito? Oi gordinho!",
    "Por que a minhoca foi ao psicólogo? Porque ela tinha muitas questões existenciais!",
    "O que a formiga foi fazer no hospital? Levar o formigalho!",
    "Qual é o prato mais valente? O macarrão à bolonhesa, porque ele enfrenta o que vier!",
    "Por que o elefante não pega fogo? Porque ele já é cinza!",
    "O que é um pontinho amarelo na sala de aula? Um aluno de castigo!",
    "Qual é o lanche preferido do louco? Sanduíche maluco-quentinho!",
    "Por que a aranha é a melhor amiga da mosca? Porque ela é inseparável!",
    "Qual é o cachorro que não late? O cachorro-quieto!",
    "O que a água disse para a outra? Se você me contar, eu te dou um copo!",
    "Qual é o cúmulo da lerdeza? Correr atrás de um ônibus parado!",
    "Qual é o cereal mais militar? O Cornflakes, porque ele está sempre em forma!",
    "O que o pneu falou para o carro? Não enche minha paciência!",
    "Qual é o cúmulo da força? Chupar a bateria e cuspir fogo!",
    "O que a toalha falou para o chão? Não me chão, sou toalha!",
    "Qual é o cúmulo do absurdo? Dois canibais jogando Uno e comendo batatas fritas!",
    "O que o lápis falou para a borracha? Você apaga o meu passado, eu apago o seu futuro!",
    "Qual é o esporte mais cheiroso? O arremesso de cebola!",
    "O que o cachorro foi fazer na igreja? Latir para o padre!",
    "Qual é o objeto mais velho do mundo? O almanaque, porque está sempre velhaco!",
    "Por que o cinema é o lugar mais seguro do mundo? Porque tem câmeras em todos os cantos!",
    "Qual é o animal que nunca dorme? O touro, porque ele é chifrudo!",
    "O que o vidro falou para o carro? Não me quebre, sou vidraça!",
    "Qual é o mês do ano que mais chove? Julho-se!",
    "Por que o louco não usa relógio? Porque ele perde a cabeça!",
    "Porque o merlhulhar cai de costas nos mar? porque se ele cair pra frente ele cai dentro do barco",
    "O que a cadeira falou para o controle remoto? Nossa, como você é controlado!",
    "Por que a bicicleta anda em duas rodas? Porque se andasse em três, seria triciclo!",
    "Qual é o cúmulo da maldade? Colocar uma bomba embaixo da cadeira elétrica!",
    "O que o tomate foi fazer no banco? Foi pedir um empréstimo!",
    "Qual é o carro do Batman? Batmóvel de Batmanzinho!",
    "Por que a minhoca não briga? Porque ela é uma minhoquieta!",
    "O que é um pontinho vermelho no canto da parede? Uma cereja de castigo!",
  ];
  
  console.log(frasesEngracadas[0]); // Saída: "Por que o livro de matemática se suicidou? Porque tinha muitos problemas."
  