const frasesMotivacao = [
    "Acredite em si mesmo. Você é mais capaz do que imagina.",
    "Não importa o quão devagar você vá, desde que não pare.",
    "A persistência é o caminho do êxito.",
    "Acredite, você é capaz de tudo o que deseja.",
    "Nunca é tarde demais para ser quem você poderia ter sido.",
    "Acredite em seu potencial e não tenha medo de arriscar.",
    "Nada é impossível quando se tem determinação e foco.",
    "Você é o único responsável pelo seu sucesso.",
    "A motivação é o combustível que te leva mais longe.",
    "Lute pelos seus sonhos e nunca desista.",
    "Grandes conquistas exigem grandes esforços.",    
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Acredite nos seus sonhos e eles se tornarão realidade.",
    "A sua determinação é o que vai te levar além dos obstáculos.",
    "Nunca se subestime. Você é capaz de muito mais do que imagina.",
    "Encare os desafios como oportunidades de crescimento.",
    "Acredite na sua força, na sua coragem e na sua resiliência.",
    "Você é o arquiteto do seu próprio destino.",
    "Não deixe que o medo impeça você de alcançar seus objetivos.",
    "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.",
    "Nunca é tarde demais para buscar a felicidade e realizar seus sonhos.",
    "Acredite em você mesmo e no seu potencial ilimitado.",
    "Se você acreditar, você é capaz de conquistar.",
    "Não espere pela oportunidade, crie a sua própria.",
    "A força de vontade move montanhas e realiza sonhos.",
    "A motivação é o primeiro passo para o sucesso.",
    "Acredite no seu potencial e não tenha medo de brilhar.",
    "Você é capaz de superar qualquer desafio que aparecer no seu caminho.",
    "Tenha coragem de seguir em frente mesmo diante das dificuldades.",
    "Acredite na sua capacidade de aprender e crescer a cada dia.",
    "Não há limites para o que você pode alcançar com determinação.",
    "Mantenha o foco no seu objetivo e não desvie o olhar.",
    "Cada dia é uma nova oportunidade para ser melhor do que ontem.",
    "O sucesso é a soma de pequenas vitórias diárias.",
    "Nunca desista, pois você pode estar a um passo do sucesso.",
    "Acredite na sua força interior e siga em frente.",
    "Encontre a motivação dentro de você e use-a como combustível.",
    "Não tenha medo de falhar, pois é assim que se aprende e se cresce.",    
    "Persista, insista e nunca desista dos seus sonhos.",
    "Você é mais forte do que imagina. Acredite em si mesmo.",
    "O sucesso não é garantido, mas o fracasso é certo se você não tentar.",
    "Acredite na sua capacidade de superar qualquer obstáculo.",
    "Lembre-se de que a jornada é tão importante quanto o destino.",
    "Não deixe que o medo do fracasso te impeça de tentar.",
    "Você é capaz de alcançar o que deseja. Acredite em si mesmo.",
    "Mantenha a positividade e a determinação mesmo nos momentos difíceis.",
    "Acredite que cada dia é uma nova chance de recomeçar.",
    "Seja a melhor versão de si mesmo em cada dia.",
    "Acredite no seu potencial e não se compare com os outros.",
    "Nunca subestime o poder dos seus sonhos e desejos."
  ];
  
  console.log(frasesMotivacao[0]); 
  