const frasesAutoAjuda = [
    "Acredite em si mesmo e todo o resto se encaixará. Tenha fé em seus próprios poderes.",
    "A maior descoberta de todos os tempos é que uma pessoa pode mudar sua vida mudando sua atitude mental.",
    "Acredite que você pode e você está no meio do caminho.",
    "Nunca é tarde demais para ser quem você poderia ter sido.",
    "O único limite para o nosso amanhã de crescimento será nossas dúvidas de hoje.",
    "Você é capaz de muito mais do que imagina.",
    "Não espere por circunstâncias ideais. Crie-as.",
    "A vida não é sobre esperar a tempestade passar, é sobre aprender a dançar na chuva.",
    "Tudo o que você sempre quis está do outro lado do seu medo.",
    "O segredo para seguir em frente é começar.",
    "Você não falhará se não desistir.",
    "Quando uma porta da felicidade se fecha, outra se abre, mas costumamos ficar olhando tanto tempo para a porta fechada que não vemos a que foi aberta para nós.",
    "Acredite em você mesmo, em seus talentos e em suas habilidades. Ninguém pode fazer você se sentir inferior sem o seu consentimento.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "A felicidade não é a ausência de problemas, mas a habilidade de lidar com eles.",
    "O que você pensa, você se torna. O que você sente, você atrai. O que você imagina, você cria.",
    "Acredite que tudo acontece por uma razão e confie no processo.",
    "Não deixe que o medo te impeça de alcançar seus sonhos.",
    "Mantenha o foco no presente e construa um futuro melhor.",
    "Acredite na sua força interior e supere todos os desafios.",
    "Cada dia é uma nova oportunidade para ser uma versão melhor de si mesmo.",
    "A gratidão transforma o que temos em suficiente.",
    "Lembre-se de cuidar de si mesmo. Você é importante.",
    "Acredite na sua capacidade de aprender, crescer e se transformar.",
    "Permita-se ser vulnerável. É assim que você encontra sua verdadeira força.",
    "Valorize cada pequena conquista ao longo do caminho.",
    "Acredite que você merece amor, felicidade e sucesso.",
    "Aprenda com seus erros e use-os como degraus para o sucesso.",
    "Você é único e especial. Celebre sua individualidade.",
    "Nunca subestime o poder de suas palavras e pensamentos positivos.",
    "Acredite em seu potencial ilimitado e no poder dos seus sonhos.",
    "Perdoe-se e liberte-se do peso do passado.",
    "Cultive a autoaceitação e ame-se como você é.",
    "Acredite que cada desafio é uma oportunidade para crescer e evoluir.",
    "Seja gentil consigo mesmo. Você está fazendo o melhor que pode.",
    "Confie na sua intuição. Ela sempre guia você na direção certa.",
    "Você tem dentro de si a coragem para enfrentar qualquer adversidade.",
    "Acredite que o universo está conspirando a seu favor.",
    "Tenha paciência. O tempo certo trará as coisas certas.",
    "Seja grato pelo que você tem e concentre-se nas bênçãos da vida.",
    "Acredite na sua capacidade de superar desafios e alcançar o sucesso.",
    "Valorize seu próprio valor e nunca se compare aos outros.",
    "Acredite que cada novo dia traz consigo novas possibilidades.",
    "Nunca desista de si mesmo. Você é capaz de coisas incríveis.",
    "Lembre-se de respirar fundo e encontrar calma no momento presente.",  
    "Acredite no poder da sua resiliência. Você é capaz de se recuperar e se fortalecer.",
    "Confie no seu processo de crescimento pessoal. Cada passo importa, por menor que seja.",
    "Permita-se abraçar o desconforto do crescimento. Grandes transformações surgem de experiências desafiadoras.",
    "Acredite que você possui a sabedoria interna necessária para tomar decisões sábias em sua vida.",
    "Seja paciente consigo mesmo. O progresso é construído um dia de cada vez."
];
  
console.log(frasesAutoAjuda[0]);
